### PR TITLE
Fix minor number for partitions while probing part entries

### LINKED ISSUE #425: direct-csi format wrong drives
Hello team, I have a machine with 2 nvme disks
```sh
$ lsblk
nvme1n1     259:0    0 465.8G  0 disk 
├─nvme1n1p1 259:2    0 402.4G  0 part /
├─nvme1n1p2 259:3    0    48M  0 part /boot/efi
└─nvme1n1p3 259:4    0  63.3G  0 part 
nvme0n1     259:1    0 465.8G  0 disk 
├─nvme0n1p1 259:7    0    50G  0 part 
├─nvme0n1p2 259:8    0   200G  0 part 
└─nvme0n1p3 259:10   0 215.8G  0 part
```
```sh
$ kubectl direct-csi drives ls -a
 DRIVE          CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE                ACCESS-TIER  STATUS
 /dev/nvme0n11  50 GiB    50 GiB     -           -        machine-38          -            Unavailable
 /dev/nvme0n12  200 GiB   200 GiB    -           -        machine-38          -            Available
 /dev/nvme0n13  216 GiB   216 GiB    -           -        machine-38          -            Available
 /dev/nvme1n11  402 GiB   156 GiB    ext4        -        machine-38          -            Available
 /dev/nvme1n12  48 MiB    7.3 MiB    fat32       -        machine-38          -            Unavailable
 /dev/nvme1n13  63 GiB    63 GiB     -           -        machine-38          -            Available
```
And I run direct-csi format drives using command `kubectl direct-csi drives format --nodes=machine-38 --drives='/dev/nvme0n12,/dev/nvme0n13' --force` then I check the drives status
```sh
$ kubectl direct-csi drives ls -a
 DRIVE          CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE                ACCESS-TIER  STATUS                                                              
 /dev/nvme0n11  50 GiB    50 GiB     -           -        machine-38          -            Unavailable                                                         
 /dev/nvme0n12  200 GiB   200 GiB    -           -        machine-38          -            Available*    failed to unmount drive ; no such file or directory   
 /dev/nvme0n13  216 GiB   153 GiB    xfs         -        machine-38          -            Ready                                                               
 /dev/nvme1n11  402 GiB   156 GiB    ext4        -        machine-38          -            Available                                                           
 /dev/nvme1n12  48 MiB    7.3 MiB    fat32       -        machine-38          -            Unavailable                                                         
 /dev/nvme1n13  63 GiB    63 GiB     -           -        machine-38          -            Available
```
```sh
$ lsblk
nvme1n1     259:0    0 465.8G  0 disk 
├─nvme1n1p1 259:2    0 402.4G  0 part /
├─nvme1n1p2 259:3    0    48M  0 part /boot/efi
└─nvme1n1p3 259:4    0  63.3G  0 part /var/lib/direct-csi/mnt/f322df92-f86c-473f-895a-2bd2cbdb1538
nvme0n1     259:1    0 465.8G  0 disk 
├─nvme0n1p1 259:7    0    50G  0 part 
├─nvme0n1p2 259:8    0   200G  0 part 
└─nvme0n1p3 259:10   0 215.8G  0 part
```
I found that I run direct-csi format for 2 partiotions `nvme0n1p2` & `nvme0n1p3` of disk **`nvme0n1`** but it's formated 2 partitions `nvme1n1p2` & `nvme1n1p3` of disk **`nvme1n1`**. I think direct-csi formatted wrong drive.

### PR DESCRIPTION
**Pull request by Praveenrajmani**
fetch the minor and partnum from uevent file instead of calculating based on the order of part-entry.

Fixes #425

### CODE REVIEW

File: pkg/sys/drive_formatter_other.go [hunk 1]
```diff
@@ -1,3 +1,4 @@
+//go:build !linux
```
Comment (balamurugana) [inline pkg/sys/drive_formatter_other.go:1]: Can you revert files having only this change?

**Review by balamurugana — APPROVED** [review]
